
<package format="3">
  <name>rover_status</name>
  <version>0.0.1</version>
  <description>Generated ROS 2 Python package</description>
  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>
  <build_depend>ament_cmake</build_depend>
  <exec_depend>rclpy</exec_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>
</package>
